apiVersion: v1
kind: Service
metadata:
  name: flask
  namespace: ns-fii
spec:
  type: LoadBalancer
  loadBalancerIP: 20.124.43.86
  ports:
  - port: 5001 
    targetPort: 5001
  selector:
    app: flask
    
